### PR TITLE
Refactord MergeSprites

### LINKED ISSUE #21: Refactor MergeSprites to use the params keyword
Refactor Extensions.MergeSprites to look like this:

```
MergeSprites(this Sprite main, params Sprite[] overlay)
```

Please adjust the behaviour of the method to have the desired effect and change all the calls to match the new parameters. Also change the contents of the summary block.

### PR DESCRIPTION
**Pull request by RishiKumarRay**
fixed #21

### CODE REVIEW

**Review by ender-titan1 — CHANGES_REQUESTED** [review]
Hello,
Instead of doing
```
 this.ImageWithSlot = sprite = sprite1.MergeSprites(sprite2)
```
please do 
```
 this.ImageWithSlot = baseSprite.MergeSprites(Image)
```

also, `MergeSprites` is an extension method meaning it can be found in `Extensions.cs` in the  `Util` folder. Please change the parameters of the method to 
```
MergeSprites(this Sprite main, params Sprite[] overlay)
```
You should also make a new array variable in the method and set it to the main sprite plus each of the overlay sprites (the main sprite should have an index of 0)

**Comment by RishiKumarRay** [comment]
I am sorry, I won't be able to do last  new array variable in the method because i don't have much knowledge about c# , I thought i have to just refactor this changes thats why I picked up the issue

**Comment by ender-titan1** [comment]
That is fine, I can do the last part on my own.

**Comment by RishiKumarRay** [comment]
@ender-titan1 Thank you , I have updated please let me know if there is any mistake or need changes

**Review by ender-titan1 — CHANGES_REQUESTED** [review]
@RishiKumarRay Just some semi-colons missing at the end of the lines. Other than that it looks good.

**Comment by RishiKumarRay** [comment]
@ender-titan1 Done , Thank You

**Review by ender-titan1 — APPROVED** [review]
Looks good!

**Pull request merged**
